<?xml version="1.0" encoding="utf-8"?><Database Name="ShopHoa" Class="dbShopHoaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.DangKy" Member="DangKies">
    <Type Name="DangKy">
      <Column Name="MaDangKy" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VaiTroNguoiDung" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="DangKy_KhachHang" Member="KhachHangs" ThisKey="MaDangKy" OtherKey="MaDangKy" Type="KhachHang" />
    </Type>
  </Table>
  <Table Name="dbo.MauSac" Member="MauSacs">
    <Type Name="MauSac">
      <Column Name="MaMau" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMau" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="MauSac_Hoa" Member="Hoas" ThisKey="MaMau" OtherKey="MaMau" Type="Hoa" />
    </Type>
  </Table>
  <Table Name="dbo.DoanhThu" Member="DoanhThus">
    <Type Name="DoanhThu">
      <Column Name="MaDoanhThu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayGiaoHang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongDoanhThu" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="DonDatHang_DoanhThu" Member="DonDatHang" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DonDatHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonDatHang" Member="DonDatHangs">
    <Type Name="DonDatHang">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDatHang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DiaChiGiaoHang" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThaiDonHang" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TongGiaTriDonHang" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="DonDatHang_DoanhThu" Member="DoanhThus" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DoanhThu" />
      <Association Name="KhachHang_DonDatHang" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GioHang" Member="GioHangs">
    <Type Name="GioHang">
      <Column Name="MaGioHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Hoa_GioHang" Member="Hoa" ThisKey="MaHoa" OtherKey="MaHoa" Type="Hoa" IsForeignKey="true" />
      <Association Name="KhachHang_GioHang" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hoa" Member="Hoas">
    <Type Name="Hoa">
      <Column Name="MaHoa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenHoa" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MoTaHoa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(10,3) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongTonKho" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiHoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaMau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnhHoa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Hoa_GioHang" Member="GioHangs" ThisKey="MaHoa" OtherKey="MaHoa" Type="GioHang" />
      <Association Name="MauSac_Hoa" Member="MauSac" ThisKey="MaMau" OtherKey="MaMau" Type="MauSac" IsForeignKey="true" />
      <Association Name="LoaiHoa_Hoa" Member="LoaiHoa" ThisKey="MaLoaiHoa" OtherKey="MaLoaiHoa" Type="LoaiHoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDangKy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="KhachHang_DonDatHang" Member="DonDatHangs" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="DonDatHang" />
      <Association Name="KhachHang_GioHang" Member="GioHangs" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="GioHang" />
      <Association Name="DangKy_KhachHang" Member="DangKy" ThisKey="MaDangKy" OtherKey="MaDangKy" Type="DangKy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHoa" Member="LoaiHoas">
    <Type Name="LoaiHoa">
      <Column Name="MaLoaiHoa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiHoa" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MoTaLoaiHoa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LoaiHoa_Hoa" Member="Hoas" ThisKey="MaLoaiHoa" OtherKey="MaLoaiHoa" Type="Hoa" />
    </Type>
  </Table>
</Database>